# Railway Backend Service Configuration
PYTHON_VERSION=3.12

# Build
[build]
builder = "NIXPACKS"

# Environment variables needed
[env]
GEMINI_API_KEY = "$GEMINI_API_KEY"
PORT = "8000"

# Start command
[deploy]
startCommand = "cd backend && pip install -r requirements.txt && python run.py"

# Health check
[healthcheck]
path = "/health"
port = 8000
