[build]
builder = "NIXPACKS"

[build.env]
NODE_VERSION = "18"
PYTHON_VERSION = "3.12"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"
ENVIRONMENT = "production"

[[services]]
serviceName = "backend"
source = "backend/"
rootDirectory = "backend"
